title: CIS 438
description: Tutorials and structure of CIS 438 at UMA for Fall 2025.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Nate LaClaire
repo_url: "https://github.com/natelaclaire/cis438"
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist

url: "https://natelaclaire.me"
exclude:
- "*-slides.md"
- README.md
